# Additional configuration and services that are needed to support integration tests
services:
  keycloak:
    image: ghcr.io/openfoodfacts/openfoodfacts-auth:main
    environment:
      - KEYCLOAK_ADMIN=root
      - KEYCLOAK_ADMIN_PASSWORD=test
      - KEYCLOAK_BASE_URL
      - KEYCLOAK_REALM_NAME
      - KC_SPI_EVENTS_LISTENER_REDIS_EVENT_LISTENER_REDIS_URL=redis://${REDIS_URL}
    depends_on:
      - redis
